name: KryoNet Flaky Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Clone KryoNet Repo
      run: |
        git clone https://github.com/EsotericSoftware/kryonet.git
        cd kryonet
        git checkout 03a135e2039bd7eb20e436ad70539238563d15a4

    - name: Build KryoNet without tests
      run: |
        cd kryonet
        mvn clean install -DskipTests

    - name: Test UnregisteredClassTest normally
      run: |
        cd kryonet
        mvn test -Dtest=com.esotericsoftware.kryonet.UnregisteredClassTest#testUnregisteredClasses

    - name: Install NonDex
      run: |
        cd kryonet
        mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.esotericsoftware.kryonet.UnregisteredClassTest#testUnregisteredClasses -DnondexRuns=100

